### ISSUE TITLE
failed tests

### ISSUE THREAD

**Issue by koo5** [researchstudio-sat/won-rdfimport-bot#3]
https://gist.github.com/koo5/f5b980e311818864abde970efcf936aa

**Comment by quasarchimaere** [comment]
there is currently an issue with our tests, try building the project with skip-tests then it should build fine.

mvn install -P skip-frontend,skip-matcher-uberjar,skip-bot-uberjar,skip-matcher-rescal-uberjar,skip-node-webapp-war,skip-owner-webapp-war,**skip-tests**

**Comment by fkleedorfer** [comment]
That's what @koo5 did - it seems to be a dependency problem we somehow don't see in our standard environment.

**Comment by fkleedorfer** [comment]
Thanks for reporting this, @koo5 - it has been fixed in the master branch with https://github.com/researchstudio-sat/webofneeds/pull/1313

**Comment by fkleedorfer** [comment]
... but if you need further assistance with using won-rdfimport-bot and webofneeds, feel free to post here or join the gitter channel https://gitter.im/researchstudio-sat/webofneeds and ask there!
